#!/usr/bin/env ruby
require 'highline/import'
require 'date'
Dir["./app/**/*.rb"].each { |f| require f }
Dir["./lib/*.rb"].each { |f| require f }

def print_error_message
  puts "[Help] Run as: ./concert_tracker"
end

def main_menu_prompt
  loop do
    choose do |menu|
      menu.prompt = ""
      concerts_controller = ConcertsController.new
      concert_questions_controller = ConcertQuestionsController.new
      menu.choice('Add a concert') {
        say(concert_questions_controller.ask_questions)
        exit
      }
      menu.choice('Manage concerts') {
        say(concerts_controller.list)
        exit
      }
      menu.choice('View statistics') {
        say(concerts_controller.index)
        exit
      }
      menu.choice('Exit') {
        say("Welp, seeya later\n")
        exit
      }
    end
  end
end

if ARGV.size == 0
  main_menu_prompt
else
  print_error_message
end
