#!/usr/bin/env ruby
require 'highline/import'

if ARGV.length < 1
  print "[Help] Run as: ./concert-tracker manage"
elsif ARGV.length == 1
  if ARGV[0] != 'manage'
    print "[Help] Run as: ./concert-tracker manage"
  else
    choose do |menu|
      menu.prompt = ""

      menu.choice('Add a concert') { say("Answer the following questions about the concert:\nWho was the headlining act?\n") }
      menu.choice('Manage concerts') { say("No concerts to edit. Add concerts.\n") }
      menu.choice('View statistics') { say("No concert data available. Add concerts.\n") }
      menu.choice('Exit') { say("Welp, seeya later\n") }
    end
  end
end
