#!/usr/bin/env ruby
require 'highline/import'
require 'date'
Dir["./app/**/*.rb"].each { |f| require f }
Dir["./lib/*.rb"].each { |f| require f }

def print_error_message
  puts "[Help] Run as: ./concert_tracker"
end

if ARGV.size == 0
  loop do
    choose do |menu|
      menu.prompt = ""
      concerts_controller = ConcertsController.new
      menu.choice('Add a concert') {
        say(concerts_controller.collect_concert_info)
        exit
      }
      menu.choice('Manage concerts') { say("") }
      menu.choice('View statistics') {
        say(concerts_controller.index)
        exit
      }
      menu.choice('Exit') {
        say("Welp, seeya later\n")
        exit
      }
    end
  end
else
  print_error_message
end
