#!/usr/bin/env ruby
require 'highline/import'
Dir["./app/**/*.rb"].each { |f| require f }
Dir["./lib/*.rb"].each { |f| require f }

def print_error_message
  puts "[Help] Run as: ./concert-tracker manage"
end

if ARGV.size == 1 and ARGV[0] == 'manage'
  choose do |menu|
    menu.prompt = ""
    concerts_contoller = ConcertsController.new
    menu.choice('Add a concert') { say("Answer the following questions about the concert:\nWho was the headlining act?\n") }
    menu.choice('Manage concerts') { say("") }
    menu.choice('View statistics') { concerts_contoller.index }
    menu.choice('Exit') { say("Welp, seeya later\n") }
  end
else
  print_error_message
end
